---
title: "Lab 1 - Data visualization"
subtitle: "REN R 213 - Winter 2026"
author: "Sheila Yu"
date: "Janurary 29, 2026"
format: html
editor: visual
---

# Questions

Loading Packages needed for the Lab

```{r}
install.packages('tidyverse')
library(tidyverse)
```

## Part 1

### Question 1

Creating histogram with binwidth of 100

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 100) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 100"
  )
```

Creating histogram with binwidth of 1,000

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 1000) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 1,000"
  )
```

Creating histogram with binwidth of 10,000

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 10000) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 10,000"
  )
```

Creating histogram with binwidth of 100,000

```{r}
ggplot(midwest, aes(x = popdensity)) +
  geom_histogram(binwidth = 100000) +
  labs(
    x = "Population density",
    y = "Count",
    title = "Population density of midwesten counties",
    subtitle = "Binwidth = 100,000"
  )
```

### Question 2

### Question 3

### Question 4

### Question 5

### Question 6

### Question 7

## Part 2

**Enough about the Midwest!**

### Question 8

### Question 9
